######################################################################
# Espace Gestionnaires (backoffice)
######################################################################

bankers:
  path:       /
  host:       "backoffice.banquedauphine.services"
  controller: App\Controller\BackOfficeController::index

bankers_validate_registration:
  path:       /validateRegistration/{client_id}/{decision}
  host:       "backoffice.banquedauphine.services"
  controller: App\Controller\BackOfficeController::validateRegistration
  requirements:
    client_id: '\d+'
    decision: 'OK|KO'

bankers_comptes_clients:
  path:       /comptes_clients
  host:       "backoffice.banquedauphine.services"
  controller: App\Controller\BackOfficeController::comptes

bankers_virements:
  path:       /virements
  host:       "backoffice.banquedauphine.services"
  controller: App\Controller\BackOfficeController::virements

bankers_bdd:
  path:       /bdd
  host:       "backoffice.banquedauphine.services"
  controller: App\Controller\BackOfficeController::bdd

bankers_plateforme_technique:
  path:       /plateforme
  host:       "backoffice.banquedauphine.services"
  controller: App\Controller\BackOfficeController::plateforme

backoffice_logout:
  path:       /logout
  host:       "backoffice.banquedauphine.services"

######################################################################
# Espace clients
######################################################################

ouvriruncompte:
  path:       /
  host:       "ouvrir-un-compte.banquedauphine.online"
  controller: App\Controller\InscriptionController::index
  #defaults:
  #  subdomain: m
  #requirements:
  #  subdomain: m|mobile

merci_prospect:
  path:       /
  host:       "ouvrir-un-compte.banquedauphine.online"
  controller: App\Controller\InscriptionController::merci

clients:
  path:       /
  host:       "clients.banquedauphine.online"
  controller: App\Controller\EspaceClientController::index

clients_virement_new:
  path:       /virements/nouveau
  host:       "clients.banquedauphine.online"
  controller: App\Controller\EspaceClientController::new_virement

clients_virement_beneficiaire_new:
  path:       /virements/beneficiaires/ajout
  host:       "clients.banquedauphine.online"
  controller: App\Controller\EspaceClientController::new_beneficiaire

clients_compte_details:
  path:       /comptes/{num_compte}
  host:       "clients.banquedauphine.online"
  controller: App\Controller\EspaceClientController::detail_compte

clients_logout:
  path:       /logout
  host:       "clients.banquedauphine.online"

######################################################################
# Site public
######################################################################

homepage:
  path:       /
  controller: App\Controller\MainController::index
