######################################################################
# Espace Gestionnaires (backoffice)
######################################################################

bankers:
  path:       /
  host:       "backoffice.banquedauphine.services"
  controller: App\Controller\BackOfficeController::index

bankers_list_demandes:
  path:       /demandes/client/{client_id}
  host:       "backoffice.banquedauphine.services"
  controller: App\Controller\BackOfficeController::list_demandes
  defaults:
    client_id: null

bankers_client_edit:
  path:       /client/edit/{client_id}
  host:       "backoffice.banquedauphine.services"
  controller: App\Controller\BackOfficeController::edit_client
  requirements:
    client_id: '\d+'

bankers_decouvert_edit:
  path:       /decouvert/edit/{compte_id}
  host:       "backoffice.banquedauphine.services"
  controller: App\Controller\BackOfficeController::edit_decouvert
  requirements:
    compte_id: '\d+'

bankers_validate_registration:
  path:       /validateRegistration/{client_id}/{decision}
  host:       "backoffice.banquedauphine.services"
  controller: App\Controller\BackOfficeController::validateRegistration
  requirements:
    client_id: '\d+'
    decision: 'OK|KO'

bankers_validate_demande:
  path:       /validateDemande/{demande_id}/{decision}/{additional_param}
  host:       "backoffice.banquedauphine.services"
  controller: App\Controller\BackOfficeController::validateDemande
  defaults: { additional_param: '' }
  requirements:
    demande_id: '\d+'
    decision: 'OK|KO'

bankers_comptes_clients:
  path:       /comptes_clients
  host:       "backoffice.banquedauphine.services"
  controller: App\Controller\BackOfficeController::comptes

bankers_virements:
  path:       /virements
  host:       "backoffice.banquedauphine.services"
  controller: App\Controller\BackOfficeController::virements

bankers_bdd:
  path:       /bdd
  host:       "backoffice.banquedauphine.services"
  controller: App\Controller\BackOfficeController::bdd

bankers_plateforme_technique:
  path:       /plateforme
  host:       "backoffice.banquedauphine.services"
  controller: App\Controller\BackOfficeController::plateforme

backoffice_logout:
  path:       /logout
  host:       "backoffice.banquedauphine.services"

######################################################################
# Espace clients
######################################################################

ouvriruncompte:
  path:       /
  host:       "ouvrir-un-compte.banquedauphine.online"
  controller: App\Controller\InscriptionController::index
  #defaults:
  #  subdomain: m
  #requirements:
  #  subdomain: m|mobile

merci_prospect:
  path:       /
  host:       "ouvrir-un-compte.banquedauphine.online"
  controller: App\Controller\InscriptionController::merci

clients:
  path:       /
  host:       "clients.banquedauphine.online"
  controller: App\Controller\EspaceClientController::index

clients_compte_details:
  path:       /comptes/{compte_id}
  requirements:
    compte_id: '\d+'
  host:       "clients.banquedauphine.online"
  controller: App\Controller\EspaceClientController::detail_compte

clients_virement_new:
  path:       /virements/nouveau
  host:       "clients.banquedauphine.online"
  controller: App\Controller\EspaceClientController::new_virement

clients_virement_beneficiaire_new:
  path:       /virements/beneficiaires/ajout
  host:       "clients.banquedauphine.online"
  controller: App\Controller\EspaceClientController::new_beneficiaire

clients_demander:
  path:       /demander/{article}/{confirm}
  host:       "clients.banquedauphine.online"
  controller: App\Controller\EspaceClientController::commander
  requirements:
    article: 'autorisation-decouvert|compte-epargne|compte-joint|chequier|cb|beneficiaire-virement'
  defaults:
    confirm: null

clients_commander_chequier:
  path:       /commander/chequier/{confirm}
  host:       "clients.banquedauphine.online"
  controller: App\Controller\EspaceClientController::commander
  defaults:
    article: "chequier"
    confirm: null

clients_commander_cb:
  path:       /commander/cb/{confirm}
  host:       "clients.banquedauphine.online"
  controller: App\Controller\EspaceClientController::commander
  defaults:
    article: "cb"
    confirm: null

clients_auth_pad:
  path: /auth/pad
  host: "clients.banquedauphine.online"
  controller: App\Controller\EspaceClientController::auth_pad

clients_profile:
  path: /profile
  host: "clients.banquedauphine.online"
  controller: App\Controller\EspaceClientController::profile

clients_logout:
  path:       /logout
  host:       "clients.banquedauphine.online"

######################################################################
# Site public
######################################################################

homepage:
  path:       /
  controller: App\Controller\MainController::index

ouvriruncompte2:
  path:       /ouvrir-un-compte
  #host:       "ouvrir-un-compte.banquedauphine.online"
  controller: App\Controller\InscriptionController::index

